### PR TITLE
Make setup-ephemeral-storage.py Python 2/3 compatible

### LINKED ISSUE #89: Exception if python binary != python2.7 on nodes
I'm using a modified AMI `Amazon Linux AMI release 2015.09`, which seems to default to python 2.6 when firing `python`. On cluster launch I get:

```
[52.37.134.99] Configuring ephemeral storage...
At least one node raised an error: Traceback (most recent call last):
  File "/tmp/setup-ephemeral-storage.py", line 158, in <module>
    non_root_block_devices = get_non_root_block_devices()
  File "/tmp/setup-ephemeral-storage.py", line 53, in get_non_root_block_devices
    block_devices_raw = subprocess.check_output([
AttributeError: 'module' object has no attribute 'check_output'
```

This is from using python 2.6:
```
root@ip-172-31-30-154 tmp]$ python26 --version
Python 2.6.9
root@ip-172-31-30-154 tmp]$ python26 setup-ephemeral-storage.py 
Traceback (most recent call last):
  File "setup-ephemeral-storage.py", line 158, in <module>
    non_root_block_devices = get_non_root_block_devices()
  File "setup-ephemeral-storage.py", line 53, in get_non_root_block_devices
    block_devices_raw = subprocess.check_output([
AttributeError: 'module' object has no attribute 'check_output'
```

Python 2.7 is in the path but it isn't called
```
root@ip-172-31-30-154 tmp]$ python27 --version
Python 2.7.10
root@ip-172-31-30-154 tmp]$ python27 /tmp/setup-ephemeral-storage.py 
{"ephemeral": ["/media/ephemeral0", "/media/ephemeral1"], "root": "/media/root"}
```

Python 3.5 also fails for me:
```
root@ip-172-31-30-154 tmp]$ python3.5 setup-ephemeral-storage.py 
Traceback (most recent call last):
  File "setup-ephemeral-storage.py", line 171, in <module>
    format_devices(ephemeral_devices)
  File "setup-ephemeral-storage.py", line 102, in format_devices
    "Format process returned non-zero exit code: {c}".format(c=return_code))
Exception: Format process returned non-zero exit code: 1
```

Based on https://github.com/nchammas/flintrock/blob/master/flintrock/core.py#L481 and these exceptions, it seems like `python` from the PATH must be _only_ 2.7 in order for for `setup-ephemeral-storage.py` to work.

### PR DESCRIPTION
**Pull request by nchammas**
Since we don't tightly control what Python is running on the cluster instances, we should make this script Python 2/3 compatible.

Specifically, `setup-ephemeral-storage.py` will now work with Python 2.7+ and 3.4+.

Fixes #89.

### CODE REVIEW

**Comment by nchammas** [comment]
@ereed-tesla - Wanna give this PR a quick whirl to make sure it works on AMIs where Python 3 is the default?
